spring.application.name=motorcycles-managment

server.port=8666

# H2 - Configuracion Inicial

spring.datasource.url=jdbc:h2:mem:motorcycles
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA - Configuracion incial

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

#H2 Console - Interfaz grafica de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Controla el comportamiento de inicialización (always asegura que se ejecute en H2)
spring.sql.init.mode=always
